### ISSUE TITLE
SQLAlchemy 2.0.0b1 breaking API changes

### ISSUE THREAD

**Issue by woutdenolf** [xraypy/XrayDB#22] opened 2022-10-14 13:23 UTC
https://docs.sqlalchemy.org/en/20/changelog/changelog_20.html#change-2.0.0b1

```
pip install --pre xraydb

Collecting sqlalchemy
  Downloading SQLAlchemy-2.0.0b1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
```

```python
(py37) denolf@lindenolf:/home/denolf/dev/pypushflow$ python -c "from xraydb import guess_edge; print(guess_edge(7.1))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/users/denolf/virtualenvs/pybox_1uQ7du/ubuntu_20_04/py37/lib/python3.7/site-packages/xraydb/xray.py", line 665, in guess_edge
    xdb = get_xraydb()
  File "/users/denolf/virtualenvs/pybox_1uQ7du/ubuntu_20_04/py37/lib/python3.7/site-packages/xraydb/xray.py", line 156, in get_xraydb
    _xraydb = XrayDB()
  File "/users/denolf/virtualenvs/pybox_1uQ7du/ubuntu_20_04/py37/lib/python3.7/site-packages/xraydb/xraydb.py", line 84, in __init__
    raise ValueError("'%s' is not a valid X-ray Database file!" % dbname)
ValueError: '/users/denolf/virtualenvs/pybox_1uQ7du/ubuntu_20_04/py37/lib/python3.7/site-packages/xraydb/xraydb.sqlite' is not a valid X-ray Database file!
```

**Comment by newville** [comment] 2022-10-14 13:35
@woutdenolf Thanks.  No idea what is happening, but I'll investigate.

**Comment by newville** [comment] 2022-10-14 16:13
@woutdenolf I think this is now fixed in a46eef63f286afd695f663a19ec5390402dcbae7.   At least, deprecation warnings using `SQLALCHEMY_WARN_20=1` with sqlachemy 1.4.40 go away and all tests pass.  Will try to test with a real sqlalchemy 2.0 beta over the next few days, but I also see that several other codes of mine are going to need attention to work with 2.0.

**Comment by asteppke** [comment] 2023-04-21 07:57
It looks like there is still something lingering. When using xraydb 4.5.0 I can run it successfully with the PyPi package (with sqlalchemy 2.0.3 also from PyPi). 

When installing xraydb 4.5.0 from `conda-forge` and the automatic dependency of sqlalchemy 2.0.9 loading the database fails:

````
self = <xraydb.xraydb.XrayDB object at 0x7faddbae9cf0>
dbname = '/home/gitlab-runner/miniconda3/envs/cristallina/lib/python3.10/site-packages/xraydb/xraydb.sqlite'
read_only = True
    def __init__(self, dbname='xraydb.sqlite', read_only=True):
        "connect to an existing database"
        if not os.path.exists(dbname):
            parent, _ = os.path.split(__file__)
            dbname = os.path.join(parent, dbname)
            if not os.path.exists(dbname):
                raise IOError("Database '%s' not found!" % dbname)
    
        if not isxrayDB(dbname):
>           raise ValueError("'%s' is not a valid X-ray Database file!" % dbname)
E           ValueError: '/home/gitlab-runner/miniconda3/envs/cristallina/lib/python3.10/site-packages/xraydb/xraydb.sqlite' is not a valid X-ray Database file!
````

Is there anything I can help to debug this compatibility issue?

**Comment by newville** [comment] 2023-04-21 14:17
@asteppke sorry for the trouble.  I'm not sure what is going on.  

Can you provide the code that causes that?   I don't understand the part of your report that says:
 
```
self = <xraydb.xraydb.XrayDB object at 0x7faddbae9cf0>
dbname = '/home/gitlab-runner/miniconda3/envs/cristallina/lib/python3.10/site-packages/xraydb/xraydb.sqlite'
read_only = True
```

I Are you trying to use a different database file?   


If I try a fresh install to attempt to reproduce this:
```
   conda create -n py310 python=3.10 sqlalchemy
   conda activate py310
   conda install -c conda-forge xraydb
```

I then get a Python session like this:

```
(py310) ~> python
Python 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:43:39) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy, xraydb
>>> sqlalchemy.__version__, xraydb.__version__
('2.0.9', '4.5.0')
>>> xraydb.mu_elam('Cu', [10000])
array([215.98631882])

>>> xdb = xraydb.XrayDB()
>>> xdb.xray_lines('Mo', 'K')
{'Ka3': XrayLine(energy=17134.0, intensity=0.000423374, initial_level='K', final_level='L1'), 'Ka2': XrayLine(energy=17375.0, intensity=0.288884, initial_level='K', final_level='L2'), 'Ka1': XrayLine(energy=17480.0, intensity=0.550837, initial_level='K', final_level='L3'), 'Kb3': XrayLine(energy=19588.4, intensity=0.0464695, initial_level='K', final_level='M2'), 'Kb1': XrayLine(energy=19606.0, intensity=0.0897094, initial_level='K', final_level='M3'), 'Kb5': XrayLine(energy=19768.9, intensity=0.00109198, initial_level='K', final_level='M4,5'), 'Kb2': XrayLine(energy=19962.4, intensity=0.0225843, initial_level='K', final_level='N2,3')}
```

So, it seems to me like it should all be working, and it is working for me in other downstream codes too.  So, I'm not sure what is going on....

**Comment by asteppke** [comment] 2023-04-21 15:50
Mea culpa, this was happening on a CI/CD system where for some reason the update to 4.5.0 did not occur. So it was stuck on 4.4.7 in the runner but locally on the console when testing using 4.5.0.

The code is simply
````python
from xraydb import material_mu
mu = material_mu("Si", 9000)
````

and I can confirm that with 4.5.0 and sqlalchemy 2.0.9 it works nicely now. 

Sorry again for the noise.

**Comment by newville** [comment] 2023-04-21 16:38
@asteppke Thanks -- no problem.  This was a pretty serious issue and flaw in the use of sqlalchemy here that should have been fixed long ago.

**Closed by newville** 2023-04-21 16:38 UTC
